# Generated by Django 5.1.4 on 2025-05-26 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_postmodel_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilemodel',
            name='avatar',
            field=models.ImageField(blank=True, default='static/images/default_avatar.png', upload_to='avatars/'),
        ),
    ]
