# Generated by Django 5.1.4 on 2025-07-08 21:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_profilemodel_avatar'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='profilemodel',
            name='subscribers',
            field=models.ManyToManyField(blank=True, related_name='subscribed', to=settings.AUTH_USER_MODEL),
        ),
    ]
