# Generated by Django 5.1.4 on 2025-08-12 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_profilemodel_subscribers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postimage',
            name='image',
            field=models.ImageField(max_length=255, upload_to='post_images/'),
        ),
    ]
