# Generated by Django 5.1.4 on 2025-02-09 20:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_postmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postmodel',
            old_name='user',
            new_name='author',
        ),
        migrations.AddField(
            model_name='postmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='postmodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='posts/'),
        ),
        migrations.AddField(
            model_name='postmodel',
            name='text',
            field=models.TextField(blank=True),
        ),
    ]
