# Generated by Django 5.1.4 on 2025-02-20 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_tagmodel_postmodel_likes_postimage_postmodel_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postmodel',
            name='image',
        ),
    ]
